/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

declare module 'bach-napi-test'
export function loadSqlite(ipcPath: string, tableName: string, sqlitePath: string, replace: boolean): void
